source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'ReactiveSprint_Example' do
  pod 'ReactiveSprint', :path => '../'
end

target 'ReactiveSprint_Tests' do
  pod 'ReactiveSprint', :path => '../'

  pod 'Quick', '~> 0.9'
  pod 'Nimble', '~> 3.2'
end
